# Generated by Django 4.2.11 on 2024-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentproperty',
            options={'verbose_name_plural': 'Equipment Properties'},
        ),
        migrations.AddField(
            model_name='item',
            name='custom_price',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='custom_weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
