# Generated by Django 4.2.11 on 2024-04-04 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0002_alter_equipmentproperty_options_item_custom_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AddField(
            model_name='item',
            name='custom_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='custom_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_acquired',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
