# Generated by Django 4.2.11 on 2024-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0003_alter_equipment_options_item_custom_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Inventory', max_length=40),
        ),
    ]
