# Generated by Django 4.2.11 on 2024-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0004_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Inventory', max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='equipmentproperty',
            constraint=models.UniqueConstraint(fields=('equipment', 'property'), name='combination_equipment_property'),
        ),
    ]
