# Generated by Django 4.2.11 on 2024-04-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dndinventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dndinventory', '0005_alter_equipment_price_alter_equipment_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=dndinventory.models.get_admin, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
