# Generated by Django 4.2.11 on 2024-04-05 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0008_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='damage_die',
            field=models.SmallIntegerField(default=6, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
    ]
