# Generated by Django 4.2.11 on 2024-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0010_alter_item_options_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Inventory', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('character', 'name'), name='combination_character_inventory_name'),
        ),
    ]
