# Generated by Django 4.2.11 on 2024-04-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0011_alter_inventory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='custom_weight',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
    ]
