# Generated by Django 4.2.11 on 2024-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndinventory', '0013_equipment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=360, null=True),
        ),
    ]
